version: 2

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.6.3
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r dev_tools/requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}
          paths:
            - "venv"
      - run:
          command: |
            . venv/bin/activate
            pytest wolpert

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
