version: 2

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.6.3
    steps:
      - checkout
      - restore_cache:
          key: deps2-{{ .Branch }}-{{ .Revision }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r dev_tools/requirements.txt
      - save_cache:
          key: deps2-{{ .Branch }}-{{ .Revision }}
          paths:
            - "venv"
      - run:
          command: |
            . venv/bin/activate
            pytest wolpert

  build-and-test-py2:
    docker:
      - image: circleci/python:3.6.3
    steps:
      - checkout
      - restore_cache:
          key: deps2-{{ .Branch }}-{{ .Revision }}-py2
      - run:
          command: |
            sudo pip install virtualenv
            virtualenv -p python2 venv
            . venv/bin/activate
            pip install -r dev_tools/requirements.txt
            pip install -r dev_tools/requirements_py2.txt
      - save_cache:
          key: deps2-{{ .Branch }}-{{ .Revision }}-py2
          paths:
            - "venv"
      - run:
          command: |
            . venv/bin/activate
            pytest wolpert

  test-docs:
    docker:
      - image: circleci/python:3.6.3
    steps:
      - checkout
      - restore_cache:
          key: deps2-{{ .Branch }}-{{ .Revision }}
      - run:
          command: |
            . venv/bin/activate
            pip install -r docs/requirements.txt
            pip install .
      - save_cache:
          key: deps2-{{ .Branch }}-{{ .Revision }}
          paths:
            - "venv"
      - run:
          command: |
            . venv/bin/activate
            cd docs
            make doctest

  deploy:
    docker:
      - image: circleci/python:3.6.3
    steps:
      - checkout
      - restore_cache:
          key: deps2-{{ .Branch }}-{{ .Revision }}
      - run:
          name: install deploy dependencies
          command: |
            . venv/bin/activate
            pip install wheel
            pip install twine
      - save_cache:
          key: deps2-{{ .Branch }}-{{ .Revision }}
          paths:
            - "venv"
      - run:
          name: verify git tag
          command: |
            . venv/bin/activate
            python setup.py verify
      - run:
          name: create pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = caioaao" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
      - run:
          name: create and deploy packages
          command: |
            . venv/bin/activate
            python setup.py sdist
            python setup.py bdist_wheel
            twine upload dist/*

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build-and-test:
          filters:
            tags:
              only: /.*/
      - build-and-test-py2:
          filters:
            tags:
              only: /.*/
      - test-docs:
          requires:
            - build-and-test
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - test-docs
            - build-and-test
            - build-and-test-py2
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*([ab][0-9]*)?/
            branches:
              ignore: /.*/




